INSERT INTO pcw_ideologies (
    id,
    name,
    color,
    x,
    y,
    influence_power,
    attack_power,
    repair_power,
    regen,
    move_speed,
    sort_order
) VALUES
      (
          'liberal',
          'Libéral',
          '#42d392',
          54,
          50,
          12,
          9,
          8,
          6,
          10,
          1
      ),
      (
          'socialdem',
          'Social-démocrate',
          '#ffb84d',
          45,
          52,
          11,
          7,
          11,
          6,
          20,
          2
      ),
      (
          'ecologist',
          'Écologiste',
          '#7bd957',
          38,
          50,
          10,
          7,
          12,
          6,
          30,
          3
      ),
      (
          'conservative',
          'Conservateur',
          '#579dff',
          58,
          47,
          10,
          10,
          8,
          6,
          40,
          4
      ),
      (
          'sovereignist',
          'Souverainiste',
          '#ff5d6c',
          43,
          58,
          9,
          12,
          7,
          6,
          50,
          5
      ),
      (
          'libertarian',
          'Libertarien',
          '#36dce8',
          62,
          55,
          13,
          9,
          7,
          6,
          60,
          6
      )
    ON DUPLICATE KEY UPDATE
                         name = VALUES(name),
                         color = VALUES(color),
                         x = VALUES(x),
                         y = VALUES(y),
                         influence_power = VALUES(influence_power),
                         attack_power = VALUES(attack_power),
                         repair_power = VALUES(repair_power),
                         regen = VALUES(regen),
                         move_speed = VALUES(move_speed),
                         sort_order = VALUES(sort_order);
