INSERT INTO pcw_ideologies (
    id,
    name,
    color,
    x,
    y,
    influence_power,
    attack_power,
    repair_power,
    regen,
    move_speed,
    sort_order
) VALUES
      (
          'liberal',
          'Libéral',
          '#42d392',
          2.352200,
          48.856600,
          12,
          9,
          8,
          6,
          10,
          1
      ),
      (
          'socialdem',
          'Social-démocrate',
          '#ffb84d',
          4.835700,
          45.764000,
          11,
          7,
          11,
          6,
          20,
          2
      ),
      (
          'ecologist',
          'Écologiste',
          '#7bd957',
          5.724500,
          45.188500,
          10,
          7,
          12,
          6,
          30,
          3
      ),
      (
          'conservative',
          'Conservateur',
          '#579dff',
          1.444200,
          43.604700,
          10,
          10,
          8,
          6,
          40,
          4
      ),
      (
          'sovereignist',
          'Souverainiste',
          '#ff5d6c',
          -1.553600,
          47.218400,
          9,
          12,
          7,
          6,
          50,
          5
      ),
      (
          'libertarian',
          'Libertarien',
          '#36dce8',
          7.261900,
          43.710200,
          13,
          9,
          7,
          6,
          60,
          6
      )
    ON DUPLICATE KEY UPDATE
                         name = VALUES(name),
                         color = VALUES(color),
                         x = VALUES(x),
                         y = VALUES(y),
                         influence_power = VALUES(influence_power),
                         attack_power = VALUES(attack_power),
                         repair_power = VALUES(repair_power),
                         regen = VALUES(regen),
                         move_speed = VALUES(move_speed),
                         sort_order = VALUES(sort_order);
